version: "3.8"

services:
  frontend:
    build:
      context: front-end/.
      dockerfile: Dockerfile
    container_name: my-web-frontend
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/workspace
      - ./assets:/assets
    command: npm start

  backend:
    build:
      context: back-end/.
      dockerfile: Dockerfile
    container_name: my-web-backend
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./back-end:/workspace
      - ./assets:/assets
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload